name: Tests
on:
  push:
    branches:
      - github-actions
env: 
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: root

jobs:
  RunTest:
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
    container:
      image: ggmartinez/imagencita
    steps:
      - name: Copiar archivo .env
        run: cp .env.example .env 
      - name: Instalar paquetes de Composer 
        run: composer install 
      - name: Ejecutar migraciones 
        run: php artisan migrate 
      - name: Ejecutar seeders 
        run:  |
          php artisan db:seed --class=EspectaculoSeeder
          php artisan db:seed --class=ServiciosEsencialesSeeder
      - name: Ejecutar pruebas
        run: php artisan test